Development aeron
rjpablo/Dribbly.WebClient pull request #9
Opened 2023-10-16 16:28 UTC by aeron-pablo23

HOOP-287: Display "Busy" Indicator When Changing Profile Picture
HOOP-298: Show Busy Indicator When Changing Team Logo

2023-10-16 16:45 UTC, rjpablo requested changes

2023-10-16 16:45 UTC, rjpablo commented on Dribbly.Web/wwwroot/src/modules/main/containers/accountviewercontainer/accountviewercontainer.component.html
> +                                        ng-if="!avc.isOwned || ('Account.UpdateNotOwned' | drbblyPermission)"
This will allow users to change other users' profile photo

2023-10-16 16:45 UTC, rjpablo commented on Dribbly.Web/wwwroot/src/modules/main/containers/accountviewercontainer/accountviewercontainer.component.js
> +                                avc.overlay.setToReady();
The overlay should also be cleared in case the upload fails.

2023-10-19 16:55 UTC, aeron-pablo23 commented on Dribbly.Web/wwwroot/src/modules/main/containers/accountviewercontainer/accountviewercontainer.component.html
> +                                        ng-if="!avc.isOwned || ('Account.UpdateNotOwned' | drbblyPermission)"
@ accountviewercontainer --> avc.onProfilePhotoClick : I added function to prevent users to change other users' profile photo.

2023-10-26 10:40 UTC, rjpablo approved these changes

2023-10-26 10:41 UTC, merged